### ISSUE TITLE
Build and run of  'generic' example fails

### ISSUE THREAD

**Issue by cklb** [umit-iace/tool-pywisp#141]
For the server part the following issues where encountered:

1.  ` cmake -S . -B build` fails with:
```
  CMake Error at CMakeLists.txt:19 (find_package):
  Could not find a package configuration file provided by "Eigen3" (requested
  version 3.3) with any of the following names:
```
This can be fixed by installing eigen, is it really needed, for the example?

2.  Next run of ` cmake -S . -B build` fails with: `ModuleNotFoundError: No module named 'sympy'`
This can be fixed by installing sympy, maybe add it to pywisps dependencies?

3. ` cmake --build build --target run ` fails with: `linux/host.h: not found`
This is probably due to the file now living in linux/sys/. However, including `<linux/sys/host.h>`
gives the Warning
```
#warning usage of <sys/host.h> has been deprecated`
#warning make use of <sys/comm.h> and/or <sys/sim.h> instead 
```
So I used `<linux/sys/comm.h>`

4. Next ` cmake --build build --target run ` fails with: 
```
tool-libs-src/./ctrl/trajectory.h:153:42: Fehler: »pow« wurde in diesem Gültigkeitsbereich nicht definiert
/server/inc/model.h:30:24: Fehler: »Buffer<double>« kann nicht nach »Eigen::DenseCoeffsBase<Eigen::Matrix<double, 1, 1, 0, 1, 1>, 1>::Scalar« {aka »double«} in Zuweisung umgewandelt werden
/server/inc/model.h:69:31: Fehler: Argumentherleitung für Klassentemplate gescheitert:
   69 |         static SeriesUnpacker su;
generic/server/src/server.cpp:23:15: Fehler: »host« wurde in diesem Gültigkeitsbereich nicht definiert
   23 |     : lineout{host.tty.out}
/generic/server/src/server.cpp:45:1: Fehler: »ExpLog« bezeichnet keinen Typ
   45 | ExpLog elog{e, k.log};
```
Of which the first one seems to come from tool-libs.

**Comment by jhalmen** [comment]
1. `Eigen` is used by the example, yes.
1. `pywisp` does _not_ itself depend on `sympy`, but the example, again, does. It is used to autocode the equations of motion of a double pendulum with the parameters found in `settings.py`.
3. and 4. fix incoming

A few things have changed indeed since this example was set up, and we forgot to update it. Thanks for calling this in!

**Comment by cklb** [comment]
Thanks a lot for the quick fix. As tool-libs seems to progress quite swiftly, maybe we could target a certain tag instead of the master branch to avoid these problems in the future?
