### ISSUE TITLE
log output box should automatically stick to newest entry

### ISSUE THREAD

**Issue by albflo** [umit-iace/tool-pywisp#46]
currently if the gui gets opened, it shows the oldest entry and only after scrolling down it sticks to the newest ones

If this behavior is desired in that way, simply delete this issue

**Comment by gruberth** [comment]
Problem is probably caused by `os.environ['QT_AUTO_SCREEN_SCALE_FACTOR'] = "1"` in `__init__.py`.

**Comment by gruberth** [comment]
The problem still exists sometimes. I think the best solution is to always scroll down if a new entry is getting appended:

Remove:

- https://github.com/umit-iace/tool-pywisp/blob/ef315a5562fe5df68f3af46682fa74d75c021431/pywisp/gui.py#L219
- https://github.com/umit-iace/tool-pywisp/blob/ef315a5562fe5df68f3af46682fa74d75c021431/pywisp/gui.py#L221

Add `self.cb.moveCursor(QTextCursor.End)` after:
https://github.com/umit-iace/tool-pywisp/blob/ef315a5562fe5df68f3af46682fa74d75c021431/pywisp/utils.py#L142
