### ISSUE TITLE
Remote widget update

### ISSUE THREAD

**Issue by jhalmen** [umit-iace/tool-pywisp#58]
i have two remotes that act on the same parameter (a slider and a pushbutton). both correctly update the parameter in the parameter list, but currently the pushbutton cannot update the slider position. it would be nice if the slider would actually be locked to the parameter value and always displays the correct value.

**Comment by gruberth** [comment]
Maby also when a param gets updated in the list

**Comment by gruberth** [comment]
Added a possible solution to update the slider in 5fc0f9d.
Its only a temporarily workaround and should be totally fixed when new object orientated param handling gets implemented.

**Comment by jhalmen** [comment]
thanks, works beautifully!
