### ISSUE TITLE
Update pymoskito

### ISSUE THREAD

**Issue by gruberth** [umit-iace/tool-pywisp#61]
Its not the right place to post the issue, but since i have no permissions to open a issue in the pymoskito repo, i will do it here.

It would be nice if the following features could also be available in pymoskito:
- [ ] choosing the visualization in the .sreg file
- [ ] the new plotting features like bbb1a90e5ff3a4f48db61fb32e75abde52c9df36 and ddc8afaa80d54f77f66a4e38fb4f2060e9c7cacb
- [ ]  show the icons in the menu bar in correct size on high resolution screens
- [ ] maybe also the pinned default docks from 550e2bdc7afaa5f40f0dcc115d58cb5fb4dd6f7a and 54519fe828e2e609ee658d3015e90f1511bc6f4a

**Comment by TanDro** [comment]
I have added the issue section at pymoskito repo. Please move this request.
