### ISSUE TITLE
Slider resolution

### ISSUE THREAD

**Issue by jhalmen** [umit-iace/tool-pywisp#68]
would it be difficult to set a custom slider resolution?
i.e.  the current minimum slider step is 1 (it needs to be an int), i would however need a slider that can do smaller steps. or alternatively an overall slider factor that i can choose.
Goal: Slider from -1 to 1, stepsize: 0.01
alternatively: Slider from -100 to 100, stepsize: 1, factor: 1/100

**Comment by TanDro** [comment]
A double slider is added. Feel free to test the new functionality. However, it must be added some range checks for the input.

**Comment by jhalmen** [comment]
see #69
