### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by TanDro** [umit-iace/tool-pywisp#74]
Add sections for:

- [x] Heartbeat
- [x] Remote widgets
- [x] Plot config
- [x] defaults.sreg (controls for plots)
- [x] Check examples

**Comment by TanDro** [comment]
@jhalmen it is possible to turn off the heartbeat or it is now a standard ping, that is always send? If it can be disabled, it is needed to do this. A possibility could be to disbale, when the hearbeattime is zero.

**Comment by jhalmen** [comment]
added conditional timer enable in #75

**Comment by TanDro** [comment]
Alright thank you.
