### ISSUE TITLE
Arduino example bug

### ISSUE THREAD

**Issue by tappeluk** [umit-iace/tool-pywisp#77]
In der klasse Transport.cpp:
In Zeile 54 sollte this->bActivateExperiment); auf true gesetzt werden, damit die Komuniktion mit python funktioniert?

In server.ino: 
In Zeile eine nicht definierte Funktion sei(); aufgerufen. 
In Zeile 13 ist ein typo unterlaufen unsigend.

**Comment by jhalmen** [comment]
> this->bActivateExperiment); 

ich frag mich was da passiert ist :))

> nicht definierte Funktion sei();

`sei()` aktiviert in einem normalen avr die interrupts global wieder, nachdem einer aufgerufen wurde. was fuer einen mikrocontroller verwendest du?

danke fuer's reporten! 
nehmen gerne auch patches naechstes mal xD

**Comment by tappeluk** [comment]
Danke! dann das nächste mal einen patch!
Aha ich verwende den due dieser ist ein arm daher kannte dieser vermutlich das sei() nicht. bin noch etwas beim experimentieren und würde die examples auch für das due erweitern?

**Comment by jhalmen** [comment]
kurzes [googlen](https://github.com/MarkusLange/OneWireSlave/issues/3) zeigt:
anstatt von `sei()` einfach `interrupts()` verwenden, dann sollte es passen.

funktioniert der code auch ohne die zeile?

**Comment by TanDro** [comment]
@jhalmen jetzt laufen alle Beispiele. @tappeluk ja bitte, wenn es funktioniert immer her damit.

**Comment by jhalmen** [comment]
@TanDro wenn man `interrupts()` anstatt `sei()` verwendet, funktioniert's sowohl fuer avr als auch fuer arm mikrocontroller, ich glaube die unterordner braucht es nicht

**Comment by TanDro** [comment]
ich vermute mal die Timer laufen auch anders, oder @tappeluk kann man fürn Arm die selbe Lib wie für nen Avr nutzen?

**Comment by TanDro** [comment]
glaube https://github.com/ivanseidel/DueTimer wäre hier adäquat, hab leider keinen due im labor gefunden zum schnellen testen
