### ISSUE TITLE
installation broken

### ISSUE THREAD

**Issue by priethfl** [umit-iace/tool-pywisp#80]
since ec84dce3beeb494a5883a3828f347d5a71a5fa0c

conda says: 
>error in pywisp setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'+https:/'"

**Comment by TanDro** [comment]
To localize the problem, you can do a pip freeze, so that I get an overview of your used enviroment.

In my opinion you are using an old version of distutils, please update to current and the problem should be solved.

**Comment by TanDro** [comment]
Fixed in 47931b36dc65d00c60763f3bd727e95ac2f49c52
