### ISSUE TITLE
selected datapoint color issue

### ISSUE THREAD

**Issue by jhalmen** [umit-iace/tool-pywisp#83]
datapoints selected for a specific plot each get their own color.
![image](https://user-images.githubusercontent.com/22578460/90754039-aa3b1200-e2d9-11ea-8777-c0a86e2444fe.png)

when selecting any of those datapoints, the selection color hides the datapoint's color
![image](https://user-images.githubusercontent.com/22578460/90754160-da82b080-e2d9-11ea-97a9-3d5de473ce71.png)
(issue: datapoint `US 1` has the color brown, but it look's like it would be blue, like datapoint `US 0`)

the selection should not prevent the user from knowing which color the selected datapoint has in the plot

**Comment by TanDro** [comment]
Fixed in 8b4545b
