### ISSUE TITLE
parameter sent twice

### ISSUE THREAD

**Issue by jhalmen** [umit-iace/tool-pywisp#91]
setup:
![image](https://user-images.githubusercontent.com/22578460/92618278-79d70a00-f2c0-11ea-84f6-82db509687e5.png)

if i press either of the buttons the slider correctly updates.
however, both the button press and the slider update cause the corresponding parameter list to be sent to the rig.

i found this by originally having the slider only move from 0 to 1. pressing the button `HeaterOn` would send  the correct parameter 255 to the rig, the slider however would try to also move to 255, but move only to 1 (its max). this would send the parameter 1 to the rig.

this might be a regression in #87 but i'm unable to find it

**Comment by TanDro** [comment]
see 5e09a532df9e892a76805fefe2186e8144688202, should be fix this issue
